In [2]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

1.13.1+cu117


# Introduction to Pytorch

### Creating Tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# checks the dimension of tensor
scalar.ndim

0

In [5]:
# returns tensor back as int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
# TENSOR
TENSOR = torch.tensor([[1,2,3],
                        [3,6,9],
                        [10, 11, 12],
                        [4,2,1]])

TENSOR

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [10, 11, 12],
        [ 4,  2,  1]])

In [14]:
TENSOR.shape

torch.Size([4, 3])

### Random Tensors

In [15]:
# Create a random tensors of shape (3, 4)

random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.0273, 0.8975, 0.1064, 0.4026],
         [0.5929, 0.2259, 0.3768, 0.6132],
         [0.2142, 0.4352, 0.1585, 0.9010]],

        [[0.8302, 0.1085, 0.0795, 0.2007],
         [0.4985, 0.7727, 0.2094, 0.1249],
         [0.0687, 0.1298, 0.0535, 0.5763]]])

In [16]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, and rgb
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [17]:
random_image_size_tensor

tensor([[[0.9998, 0.1078, 0.4980],
         [0.2636, 0.8255, 0.5692],
         [0.8897, 0.1020, 0.1862],
         ...,
         [0.7098, 0.3628, 0.1985],
         [0.9470, 0.5227, 0.8314],
         [0.9654, 0.6549, 0.5671]],

        [[0.2208, 0.2310, 0.2573],
         [0.4963, 0.5288, 0.5436],
         [0.5250, 0.3656, 0.5743],
         ...,
         [0.4504, 0.9030, 0.3029],
         [0.3692, 0.0015, 0.3564],
         [0.5981, 0.3516, 0.3961]],

        [[0.6538, 0.5237, 0.1635],
         [0.6821, 0.4845, 0.4885],
         [0.1274, 0.3320, 0.8815],
         ...,
         [0.7649, 0.8482, 0.0804],
         [0.3200, 0.8720, 0.3725],
         [0.4834, 0.9390, 0.8622]],

        ...,

        [[0.2554, 0.6615, 0.8161],
         [0.4093, 0.0704, 0.5745],
         [0.9568, 0.0076, 0.9294],
         ...,
         [0.7691, 0.6347, 0.1878],
         [0.7671, 0.3304, 0.9140],
         [0.7432, 0.7301, 0.6406]],

        [[0.3774, 0.2076, 0.9908],
         [0.9434, 0.3922, 0.6140],
         [0.

### Zeros and ones

In [18]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
# Returns the tensor's datatype
ones.dtype

torch.float32

### Create a range and tensors like

In [21]:
# Use torch.arange()
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensor not on the right device

In [23]:
# Setting datatype of tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, # Datatype
                               device="cuda", #By default "cpu", set device on either gpu/cpu
                               requires_grad=False) #if pytorch will track gradiants
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.], device='cuda:0'), torch.float32)

In [24]:
# Converting datatype from one to another
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16), torch.float16)

### Tensor Attributes (Getting information from tensors)

1. to get datatype: use `tensor.dtype`
2. to get shape: use `tensor.shape`
3. to get device: use `tensor.device`

In [25]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2713, 0.9430, 0.0738, 0.2812],
        [0.1235, 0.7725, 0.9729, 0.6903],
        [0.3118, 0.3305, 0.2939, 0.6749]])

In [26]:
# Findout details about some tensor
print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2713, 0.9430, 0.0738, 0.2812],
        [0.1235, 0.7725, 0.9729, 0.6903],
        [0.3118, 0.3305, 0.2939, 0.6749]])
Data type of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (Tensor Operations)

Tensor operations include: 
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [27]:
# Create a tensor & addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [28]:
# Multiply tensor (Element-Wise)
tensor * 10

tensor([10, 20, 30])

In [29]:
# Subtraction of tensor
tensor - 10

tensor([-9, -8, -7])

In [74]:
# Division of tensor
tensor / 10

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)
torch.add(tensor, 10)
torch.sub(tensor, 10)
torch.div(tensor,)

tensor([0.1000, 0.2000, 0.3000])

### Matrix multiplication

Two main ways of performing multiplication in NN & DL:
1. Element-wise multiplication
2. Matrix Multiplication - mulitply matrix with matrix (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The *inner dimensions* must match:
- `(3, 2) @ (3, 2)` won't work.
- `(2, 3) @ (3, 2)` will work
- `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the *outer dimension*:
- `(2, 3) @ (3, 2)` => (2, 2)
- `(3, 2) @ (2, 3)` => (3, 3)

In [ ]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication sample will not work.
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# Matrix multiplication sample that inner dimension match.
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.1164, 0.3126],
        [0.1300, 0.2649]])

In [ ]:
# Matrix mu ltiplication resulting shape
print(torch.matmul(torch.rand(2,3), torch.rand(3,2)).shape)
torch.matmul(torch.rand(4,3), torch.rand(3,5)).shape

torch.Size([2, 2])


torch.Size([4, 5])

### ONe of the most common errors in dep learning: Shapre Errors

In [ ]:
# Shape of matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7,8],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is same with torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### To fix our tensor shape issues, we can manilpulate the shape of one our tensor using transpose

A  *transpose* switches the axis or dimensions of a given tensor.

In [ ]:
# transposing a tensor
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [ 8, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# Applying transposed tensored

torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  30,  33],
        [ 53,  68,  75],
        [ 83, 106, 117]])

### Finding the min, max, mean, sum, etc (Tensor Aggregation)

In [ ]:
# create a tensor
x = torch.arange(start=0,end=100, step=10, dtype=torch.float64)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0., dtype=torch.float64), tensor(0., dtype=torch.float64))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90., dtype=torch.float64), tensor(90., dtype=torch.float64))

In [ ]:
# Find the mean (average)
# Must only work on float
# Converting x.type(torch.float32)
torch.mean(x), x.mean()

(tensor(45., dtype=torch.float64), tensor(45., dtype=torch.float64))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450., dtype=torch.float64), tensor(450., dtype=torch.float64))

### Finding the positional min and max

In [ ]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float64)

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum occurs.
x.argmin(), x[x.argmin()]

(tensor(0), tensor(0., dtype=torch.float64))

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax(), x[x.argmax()]

(tensor(9), tensor(90., dtype=torch.float64))

### Change tensor datatype

In [31]:
# Cretae a tensor and check its datatype
tensor = torch.arange(start=10, end=100, step=10)
tensor.dtype

torch.int64

In [33]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Reshaping, stacking, squeezing and unsqueezing

* **Reshaping** - reshapes an input tensor to a defined shape
* **View** - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* **Stacking** - combine multiple tensors on top of each otehr (vstack) or side by side (hstack).
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - add all `1` dimension to a targer tensor
* **Permute** - return a view of the input with a dimensions permuted (swapped) in a certain way.

In [34]:
# Create a tensor
import torch

x = torch.arange(start=1., end=10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [37]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [38]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [39]:
x = torch.arange(start=1., end=11)
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [41]:
# Change the view
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [42]:
# Changing z changes x (because a view of a tensor share the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [43]:
# Stack ternsors on top of each other
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [44]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [49]:
# Torch squeeze <- adds 1 dimension
x = torch.arange(start=1., end=10)
x = x.reshape(1,9)
x, x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
x.squeeze(),x.squeeze().shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
# Torch Unsqueeze <- removes 1 dimension
x = x.squeeze()
x.unsqueeze(dim=0), x.unsqueeze(dim=0).shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Torch permute
x_original = torch.rand(size=(224,224,3))

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)
x_permuted, x_permuted.shape

(tensor([[[0.0342, 0.9696, 0.2332,  ..., 0.7154, 0.8868, 0.9401],
          [0.4107, 0.0511, 0.2960,  ..., 0.1868, 0.8784, 0.6038],
          [0.9125, 0.0894, 0.7813,  ..., 0.9940, 0.4014, 0.9058],
          ...,
          [0.6394, 0.5571, 0.7354,  ..., 0.7235, 0.4902, 0.0887],
          [0.9798, 0.5459, 0.1326,  ..., 0.2332, 0.0331, 0.5872],
          [0.3690, 0.9877, 0.4922,  ..., 0.4011, 0.8538, 0.8495]],
 
         [[0.6176, 0.8192, 0.2053,  ..., 0.7366, 0.7661, 0.5650],
          [0.8914, 0.5285, 0.9509,  ..., 0.3184, 0.4543, 0.6658],
          [0.0410, 0.8550, 0.5597,  ..., 0.4296, 0.2791, 0.8998],
          ...,
          [0.9163, 0.0111, 0.8346,  ..., 0.1343, 0.6929, 0.2462],
          [0.9298, 0.0483, 0.4000,  ..., 0.4150, 0.3162, 0.0275],
          [0.3246, 0.8312, 0.0956,  ..., 0.1315, 0.2282, 0.4832]],
 
         [[0.9022, 0.7200, 0.5567,  ..., 0.0928, 0.1274, 0.6390],
          [0.2193, 0.6175, 0.1103,  ..., 0.3689, 0.1577, 0.8496],
          [0.2822, 0.1847, 0.3023,  ...,

### Selecting data (indexing)

In [61]:
x_original[0,0,0] = 72828
x_original[0,0,0]

tensor(72828.)

#### Indexing (selecting data from tensors)
Indesing with pytorch isd similar with numpy

In [62]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
# Index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [65]:
# Indexd on the middle bracket
x[0,0]

tensor([4, 5, 6])

In [67]:
# Index on the most innner bracket( lst dimension)
x[0,2,2]

tensor(9)

In [68]:
# You can also use ":" to select all the target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [71]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [72]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [73]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

### Pytorch and Numpy

Numpy is a popular scientific python numerical computing library. Pytorch has functionality to interact with Numpy.

* Data in NumPy, wnat in Pytorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `troch.Tensor.numpy`


In [76]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [77]:
array.dtype

dtype('float64')

#### Note
* Changing numpy array will not change tensor array
* Changing tensor array will not change numpy array

### Reproducbility (trying to take random out of random)

In short how a neural network learns:
`Start with random numbers -> tensor operations ->  update random numbers to try and make them better representations of the data -> again -> again`

To reduce the randomness in neural networks and Pytorch comes the concenpt of **random seed**.

In [81]:
import torch
# create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])
tensor([[0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [79]:
# Let's make some random but reproducable tensors
import torch
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and pytorch objects on the GPUS

GPUS = faster computation on numbers (CUDA)

In [83]:
# Check GPU access with pytorch
import torch
torch.cuda.is_available()

True

In [84]:
# setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

For pytorch since it's capable of running on GPU or CPU, it's best practice to setup device agnostic code:

E.G. Run GPU if avilable

In [85]:
# Count number of devices
torch.cuda.device_count()

1

In [91]:
# Create tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [92]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [95]:
# Moving tensor back to gpu. This is usefull if numpy is needed.
tensor_on_cpu = tensor.cpu().numpy()
tensor_on_cpu

array([1, 2, 3], dtype=int64)